# Generated by Django 5.0.6 on 2024-05-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=100)),
                ('service_image', models.ImageField(upload_to='uploads')),
                ('service_description', models.TextField()),
                ('service_date_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
